### ISSUE TITLE
Pixel overflow if you increase the font size on the system

### ISSUE THREAD

**Issue by ikicodedev** [ikicodedev/calendar_timeline#21]
![image](https://user-images.githubusercontent.com/5318708/98437962-ef0b6380-20e6-11eb-8a69-14b958663e4d.png)

**Comment by oaugustus** [comment]
Same here.

**Comment by RegNex** [comment]
same issue

**Comment by oaugustus** [comment]
> same issue

My solution was copy the code and change it manually as a custom class. 

Solved.

**Comment by lakoliu** [comment]
Same issue. I prefer not to copy the code and manually change it because I would like to easily update calendar_timeline in the future. @oaugustus perhaps you could submit a PR with your fix or share it here?

**Comment by ikicodedev** [comment]
To fix the problem we would have to have a dynamic height depending on the scale factor of the font. Using `MediaQuery.of(context).textScaleFactor;` we could modify the height of the containers of the different listings.

If anyone could test this solution with a PR I would be more than grateful.

**Comment by ViktorKirjanov** [comment]
Hi,
Here is my solution,
check this one please: https://github.com/ikicodedev/calendar_timeline/pull/65

Also, you can use my fork and add it into pubspec.yaml
```
dependencies:
  calendar_timeline:
    git:
      url: https://github.com/ViktorKirjanov/calendar_timeline
      ref: master # branch    
```
